<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>res\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="res\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="res\app.ico" />
  </ItemGroup>

</Project>
